### ISSUE TITLE
App is not launching on Android 10

### ISSUE THREAD

**Issue by i-shivamsoni** [udacity/ud839_ViewPager_Example#7]
As I am clicking on the run button in the android studio the app do not get launched. i am getting following error 
```
2020-04-22 14:57:20.667 7749-7862/? E/anwh: Phenotype API error. Event # cazr@bc3c3a67, EventCode: 12 [CONTEXT service_id=51 ]
    anvl: 29503
        at anwn.b(:com.google.android.gms@201216040@20.12.16 (120700-306753009):25)
        at anwh.a(:com.google.android.gms@201216040@20.12.16 (120700-306753009):90)
        at anwh.a(:com.google.android.gms@201216040@20.12.16 (120700-306753009):77)
        at aaqn.run(:com.google.android.gms@201216040@20.12.16 (120700-306753009):8)
        at blya.run(:com.google.android.gms@201216040@20.12.16 (120700-306753009):2)
        at tgn.b(:com.google.android.gms@201216040@20.12.16 (120700-306753009):12)
        at tgn.run(:com.google.android.gms@201216040@20.12.16 (120700-306753009):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at tmm.run(:com.google.android.gms@201216040@20.12.16 (120700-306753009):0)
        at java.lang.Thread.run(Thread.java:919)
2020-04-22 14:57:20.667 7749-7862/? E/AsyncOperation: serviceID=51, operation=GetCommittedConfigurationOperationCall
    OperationException[Status{statusCode=unknown status code: 29503, resolution=null}]
        at anwh.a(:com.google.android.gms@201216040@20.12.16 (120700-306753009):92)
        at anwh.a(:com.google.android.gms@201216040@20.12.16 (120700-306753009):77)
        at aaqn.run(:com.google.android.gms@201216040@20.12.16 (120700-306753009):8)
        at blya.run(:com.google.android.gms@201216040@20.12.16 (120700-306753009):2)
        at tgn.b(:com.google.android.gms@201216040@20.12.16 (120700-306753009):12)
        at tgn.run(:com.google.android.gms@201216040@20.12.16 (120700-306753009):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at tmm.run(:com.google.android.gms@201216040@20.12.16 (120700-306753009):0)
        at java.lang.Thread.run(Thread.java:919)
2020-04-22 14:57:20.668 7749-7907/? E/NetRec: [603] akzh.a: Could not retrieve server token for package com.google.android.apps.gcs
    java.util.concurrent.ExecutionException: sbt: 29503: 
        at aupu.b(:com.google.android.gms@201216040@20.12.16 (120700-306753009):5)
        at aupu.a(:com.google.android.gms@201216040@20.12.16 (120700-306753009):23)
        at akzh.a(:com.google.android.gms@201216040@20.12.16 (120700-306753009):1)
        at akzh.a(:com.google.android.gms@201216040@20.12.16 (120700-306753009):4)
        at akzg.getHeaders(:com.google.android.gms@201216040@20.12.16 (120700-306753009):2)
        at com.android.volley.toolbox.HttpClientStack.performRequest(:com.google.android.gms@201216040@20.12.16 (120700-306753009):18)
        at szt.performRequest(:com.google.android.gms@201216040@20.12.16 (120700-306753009):1)
        at blv.executeRequest(:com.google.android.gms@201216040@20.12.16 (120700-306753009):1)
        at com.android.volley.toolbox.BasicNetwork.performRequest(:com.google.android.gms@201216040@20.12.16 (120700-306753009):9)
        at szu.performRequest(:com.google.android.gms@201216040@20.12.16 (120700-306753009):14)
        at com.android.volley.NetworkDispatcher.a(:com.google.android.gms@201216040@20.12.16 (120700-306753009):6)
        at com.android.volley.NetworkDispatcher.run(:com.google.android.gms@201216040@20.12.16 (120700-306753009):2)
     Caused by: sbt: 29503: 
        at shg.a(:com.google.android.gms@201216040@20.12.16 (120700-306753009):4)
        at anvv.b(:com.google.android.gms@201216040@20.12.16 (120700-306753009):3)
        at anwn.a(:com.google.android.gms@201216040@20.12.16 (120700-306753009):8)
        at aaqn.run(:com.google.android.gms@201216040@20.12.16 (120700-306753009):14)
        at blya.run(:com.google.android.gms@201216040@20.12.16 (120700-306753009):2)
        at tgn.b(:com.google.android.gms@201216040@20.12.16 (120700-306753009):12)
        at tgn.run(:com.google.android.gms@201216040@20.12.16 (120700-306753009):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at tmm.run(:com.google.android.gms@201216040@20.12.16 (120700-306753009):0)
        at java.lang.Thread.run(Thread.java:919)
2020-04-22 14:57:20.670 7749-7907/? W/NetRec: [603] akzh.a: No server tokens extracted.
2020-04-22 14:57:20.975 2036-2063/? E/memtrack: Couldn't load memtrack module
2020-04-22 14:57:20.975 2036-2063/? W/android.os.Debug: failed to get memory consumption info: -1
2020-04-22 14:57:20.977 7759-8074/? I/Vision: Requesting optional module download of ocr.
2020-04-22 14:57:20.985 7759-8074/? I/Vision: Checking for download completion for 1179758 -- ocr
2020-04-22 14:57:21.443 7749-8106/? I/NetRec: [635] NetRecChimeraGcmTaskService.a: Completed rapid_refresh_scores_task score refresh task in 788 ms, returning 0
2020-04-22 14:57:21.601 1792-2477/? E/GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
2020-04-22 14:57:21.601 1792-2477/? E/GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
2020-04-22 14:57:21.810 7759-7891/? W/FontsContentProvider: Fetch {Noto Color Emoji Compat, wdth 100.0, wght 400, ital 0.0, bestEffort false} failed due to timeout
    java.util.concurrent.TimeoutException: Waited 10000 milliseconds (plus 1 milliseconds, 68900 nanoseconds delay) for bqve@d2f9173[status=PENDING]
        at bqry.get(:com.google.android.gms@201216040@20.12.16 (120700-306753009):39)
        at aaoy.query(:com.google.android.gms@201216040@20.12.16 (120700-306753009):12)
        at rct.query(:com.google.android.gms@201216040@20.12.16 (120700-306753009):4)
        at android.content.ContentProvider.query(ContentProvider.java:1214)
        at eam.superQuery(:com.google.android.gms@201216040@20.12.16 (120700-306753009):2)
        at com.google.android.chimera.ContentProvider.query(:com.google.android.gms@201216040@20.12.16 (120700-306753009):2)
        at rct.query(:com.google.android.gms@201216040@20.12.16 (120700-306753009):9)
        at android.content.ContentProvider.query(ContentProvider.java:1307)
        at eam.superQuery(:com.google.android.gms@201216040@20.12.16 (120700-306753009):1)
        at com.google.android.chimera.ContentProvider.query(:com.google.android.gms@201216040@20.12.16 (120700-306753009):1)
        at eam.query(:com.google.android.gms@201216040@20.12.16 (120700-306753009):2)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:267)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
```

**Comment by msmilkshake** [comment]
Hey dude, use my pull request. It works out of the box with newer Android Studio versions. I use SDK 29.
Here you go:
[https://github.com/msmilkshake/ud839_ViewPager_Example/tree/quiz](https://github.com/msmilkshake/ud839_ViewPager_Example/tree/quiz)

Cheers!!

**Comment by LiorA1** [comment]
> Hey dude, use my pull request. It works out of the box with newer Android Studio versions. I use SDK 29.
> Here you go:
> https://github.com/msmilkshake/ud839_ViewPager_Example/tree/quiz
> 
> Cheers!!

Thank's
